### ISSUE TITLE
Krun "same platform" check broken?

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#101]
Hi,

I don't understand the current implementation of `audits_same_platform`:

```
def audits_same_platform(audit0, audit1):
    """Check whether two platform audits are from identical machines.
    A machine audit is a dictionary with the following keys:

        * cpuinfo (Linux only)
        * packages (Debian-based systems only)
        * debian_version (Debian-based systems only)
        * uname (all platforms)
        * dmesg (all platforms)

    Platform information may be Unicode.
    """
    for key in ["cpuinfo", "dmesg", "uname"]:
        if (not key in audit0) or (not key in audit1):
            return False
    if not audit0["uname"] == audit1["uname"]:
        return False
    return True
```

It just checks the existence of keys, and not the content of the audit. Is that intentional? On OpenBSD this always returns `False` as `cpuinfo` is linux specific.

I think:

 * We should be checking the contents of the audits.
 * This should be hooked into the platform hierarchy. This would allow specific platform checks without too much `if linux() elif OpenBSD...`.

Thanks

**Comment by snim2** [comment]
It checks the keys and the uname, and yes this was deliberate. Our previous discussions on this covered three issues:

  1. You suggested moving this function to a method within the classes in `platform.py`. I was planning to do this as part of #75 but I'm happy to move that forward as a separate PR.
  2. There was a discussion of exactly *how* we decide that a machine is "this" machine and not another one. I suggested using `blkid` on Linux, which returns a unique ID of the root file system. I guess someone could have installed more RAM between resumes, so this doesn't catch every case, but anyhow @ltratt felt this was overkill and suggested we use `hostname`.
  3. Earlier I had a version of this method which checked *all* the values in the dictionary, including the packages. This worked up to a `--resume` with a real reboot, at which point Krun consistently told me that my laptop had been swapped for another machine between executions. It turns out that `platform.audit()` returns a `str`, but the audit in the JSON file is a `unicode`. On my machine I have packages with names that contain acutes and other accents, and a `==` between "this" platform and the previous one always returned `False`. The Internet contains a wide variety of solutions to this problem, and I didn't get any of them to quite work: hence the hack.

So, if you want this reverted to something more like its previous implementation, then that's fine, but I would appreciate some advice about point 3!

**Comment by vext01** [comment]
Thanks for the detailed description.

Given the problematic string issues, I think it's actually sufficient just to check the uname. However, note the current implemetation always returns `False` on OpenBSD. Due to:

```
for key in ["cpuinfo", "dmesg", "uname"]:
        if (not key in audit0) or (not key in audit1):
            return False
```

`cpuinfo` will never be in the audit for OpenBSD. On Linux this comes from `/proc` which is non-existent on OpenBSD. Instead OpenBSD uses the `systctl` framework. Arguably, we should amend the `OpenBSDPlatform` to include some CPU information, but that is low priority for now.

How about we just remove the above code chunk for now, then raise a low-priority bug to the effect of "same platform check is rudimentary"?
