### ISSUE TITLE
Log to file and email errors.

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#11]
As discussed with @ltratt , it should be possible to log all benchmarking output to a file and to (optionally) email errors to a configurable address.

**Comment by ltratt** [comment]
Ideally errors should be mailed out as they happen too (so one doesn't need to continuously monitor a machine). We should probably have some sort of rate limiter though otherwise you might end up with thousands of messages if a config error happens -- say if it sends more than 3 mails in an hour, it might say on the fourth one "lots of errors are happening; no more messages will be mailed".

**Comment by vext01** [comment]
Sounds reasonable.
